environment           = "staging"
gcp_project_id        = "mizaniya-ai-staging"
gcp_region            = "europe-west3"
firestore_database_id = "(default)"
allowed_origins       = "https://mizaniya-staging.mizaniya.ai"
