export type Currency = 'EGP' | 'USD' | 'SAR' | 'EUR';

export type PaymentMethod =
  | 'InstaPay'
  | 'Vodafone Cash'
  | 'CIB Bank'
  | 'Fawry'
  | 'Cash'
  | 'Visa/Mastercard'
  | 'Valu'
  | 'B.TECH / Aman';

export type CategoryType =
  | 'Food & Groceries'
  | 'Housing & Utilities'
  | 'Bills & Subscriptions'
  | 'Transport & Ride Apps'
  | 'Installments & Debt'
  | 'Health & Education'
  | 'Family & Allowances'
  | 'Shopping & Entertainment'
  | 'Emergency & Savings'
  | 'Income & Salary';

export interface Wallet {
  id: string;
  name: string;
  nameAr?: string;
  type: 'cash' | 'bank' | 'card' | 'savings' | 'wallet' | 'credit';
  balance: number;
  currency: Currency;
  accountNumber?: string;
  icon: string;
  color: string;
  isPrimary?: boolean;
}

export interface Transaction {
  id: string;
  title: string;
  amount: number;
  currency: Currency;
  type: 'expense' | 'income' | 'transfer';
  category: CategoryType;
  walletId: string;
  paymentMethod: PaymentMethod;
  date: string;
  merchant?: string;
  notes?: string;
  receiptUrl?: string;
  isDuplicate?: boolean;
  aiTag?: string;
  hasAnomaly?: boolean;
}

export interface CategoryBudget {
  category: CategoryType;
  categoryAr: string;
  allocatedAmount: number;
  spentAmount: number;
  color: string;
  icon: string;
}

export interface Budget {
  id: string;
  monthKey?: string;
  month: string;
  year: number;
  totalIncome: number;
  totalSalary: number;
  targetSavingsPercent: number;
  savingsTargetPercent: number;
  allocatedSavings: number;
  categories: CategoryBudget[];
  autoGenerated?: boolean;
}

export interface Goal {
  id: string;
  title: string;
  titleAr: string;
  targetAmount: number;
  currentAmount: number;
  targetDate: string;
  category: string;
  icon: string;
  color: string;
  monthlyTarget: number;
  riskLevel: 'Low' | 'Medium' | 'High';
  successProbability: number;
}

export interface Subscription {
  id: string;
  name: string;
  provider: string;
  amount: number;
  currency: Currency;
  cycle: 'monthly' | 'yearly';
  nextDueDate: string;
  paymentMethod: PaymentMethod;
  category: CategoryType;
  autoPay: boolean;
  icon: string;
  status: 'active' | 'paused' | 'cancelled';
}

export interface UserProfile {
  uid: string;
  displayName: string;
  email: string;
  country: string;
  currency: Currency;
  language: 'ar' | 'en';
  role: 'user' | 'admin';
  salary?: number;
  monthlyIncome?: number;
  emergencyFundMonths?: number;
  createdAt: string;
  updatedAt: string;
}

export interface InstallmentDebt {
  id: string;
  title: string;
  titleAr: string;
  principalAmount: number;
  remainingAmount: number;
  monthlyPayment: number;
  interestRate?: number;
  dueDay: number;
  provider: string; // ValU, Sympl, CIB Bank Loan, B.TECH, Aman, Credit Card
  status: 'ACTIVE' | 'PAID_OFF';
  notes?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface Bill {
  id: string;
  title: string;
  titleAr: string;
  biller: string; // e.g. شركة جنوب القاهرة للكهرباء, WE Fiber, غاز مصر
  amount: number;
  dueDate: string;
  isPaid: boolean;
  paymentMethod: PaymentMethod;
  fawryCode?: string;
  icon: string;
  urgency: 'high' | 'medium' | 'low';
}

export interface HealthScoreBreakdown {
  overallScore: number; // 0-100
  savingsRateScore: number;
  debtRatioScore: number;
  budgetDisciplineScore: number;
  emergencyFundScore: number;
  incomeStabilityScore: number;
  recommendations: string[];
}

export type AIAgentType =
  | 'coach'
  | 'budget'
  | 'savings'
  | 'debt'
  | 'fraud'
  | 'goal'
  | 'reminder';

export interface AIAgent {
  id: AIAgentType;
  name: string;
  nameAr: string;
  role: string;
  roleAr: string;
  avatarIcon: string;
  color: string;
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'ai';
  agent: AIAgentType;
  text: string;
  timestamp: string;
  source?: string;
  actions?: { label: string; actionKey: string }[];
}

export interface InsightTimelineItem {
  id: string;
  type: 'saving' | 'warning' | 'achievement' | 'milestone' | 'prediction';
  title: string;
  titleAr: string;
  description: string;
  descriptionAr: string;
  date: string;
  amountImpact?: number;
  icon: string;
  color: string;
}

export interface FamilyMember {
  id: string;
  name: string;
  role: 'Parent' | 'Spouse' | 'Child' | 'Viewer';
  monthlyAllowance?: number;
  spentThisMonth?: number;
  avatar: string;
  permissions: {
    canAddExpense: boolean;
    canViewAllWallets: boolean;
    requiresApproval: boolean;
  };
}

export interface Challenge {
  id: string;
  title: string;
  titleAr: string;
  description: string;
  durationDays: number;
  rewardPoints: number;
  badgeIcon: string;
  currentProgressPercent: number;
  isCompleted: boolean;
}

export interface FeatureFlags {
  voiceAssistant: boolean;
  emergencyMode: boolean;
  familyWallet: boolean;
  ocrReceiptScanner: boolean;
  aiAutoBudget: boolean;
  geminiProRouting: boolean;
  whatsappIntegration: boolean;
  instapayDirectSync: boolean;
}
