import React, { useState } from 'react';
import { Budget, CategoryBudget } from '../types';
import { formatCurrency } from '../utils/formatters';
import { apiClient } from '../services/apiClient';
import {
  Sparkles,
  RefreshCw,
  ShoppingBag,
  Home,
  CreditCard,
  Car,
  Coffee,
  ShieldAlert,
  AlertTriangle,
} from 'lucide-react';

interface BudgetsViewProps {
  budget: Budget;
  onUpdateBudget: (newBudget: Budget) => void;
  lang: 'ar' | 'en';
}

export const BudgetsView: React.FC<BudgetsViewProps> = ({
  budget,
  onUpdateBudget,
  lang,
}) => {
  const isAr = lang === 'ar';

  const [salaryInput, setSalaryInput] = useState((budget.totalSalary || budget.totalIncome || '').toString());
  const [savingsPercent, setSavingsPercent] = useState(budget.targetSavingsPercent || budget.savingsTargetPercent || 20);
  const [isGenerating, setIsGenerating] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleGenerateAutoBudget = async () => {
    setErrorMsg(null);
    const parsedSalary = parseFloat(salaryInput);
    if (!parsedSalary || parsedSalary <= 0) {
      setErrorMsg(isAr ? 'يرجى إدخال قيمة المرتب الشهري لحساب الميزانية.' : 'Please enter a valid monthly salary.');
      return;
    }

    setIsGenerating(true);
    try {
      const res = await apiClient.post('/ai/generate-budget', {
        salary: parsedSalary,
        savingsTargetPercent: savingsPercent,
      });

      if (!res.success || !res.data) {
        throw new Error(res.error || 'Failed to generate budget');
      }

      const generatedData = res.data;
      const now = new Date();
      const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;

      const newBudget: Budget = {
        id: monthKey,
        monthKey,
        month: now.toLocaleString(isAr ? 'ar-EG' : 'en-US', { month: 'long' }),
        year: now.getFullYear(),
        totalIncome: generatedData.totalSalary || parsedSalary,
        totalSalary: generatedData.totalSalary || parsedSalary,
        targetSavingsPercent: savingsPercent,
        savingsTargetPercent: savingsPercent,
        allocatedSavings: generatedData.allocatedSavings || Math.round(parsedSalary * (savingsPercent / 100)),
        autoGenerated: true,
        categories: (generatedData.categories || []).map((cat: any) => ({
          category: cat.name.includes('الأكل')
            ? 'Food & Groceries'
            : cat.name.includes('الفواتير')
            ? 'Housing & Utilities'
            : cat.name.includes('الأقساط')
            ? 'Installments & Debt'
            : cat.name.includes('المواصلات')
            ? 'Transport & Ride Apps'
            : cat.name.includes('الترفيه')
            ? 'Shopping & Entertainment'
            : 'Emergency & Savings',
          categoryAr: cat.name,
          allocatedAmount: cat.amount,
          spentAmount: cat.spentAmount ?? 0, // Real spent amount populated from backend
          color: '#10B981',
          icon: 'ShoppingBag',
        })),
      };

      // Persist to backend Firestore
      const saveRes = await apiClient.post('/budgets', newBudget);
      if (saveRes.success && saveRes.budget) {
        onUpdateBudget(saveRes.budget);
      } else {
        onUpdateBudget(newBudget);
      }
    } catch (err: any) {
      console.error('Failed to auto generate budget:', err);
      setErrorMsg(isAr ? 'فشل إنشاء الميزانية بالذكاء الاصطناعي.' : 'Failed to generate budget via AI.');
    } finally {
      setIsGenerating(false);
    }
  };

  const getCategoryIcon = (catName: string) => {
    switch (catName) {
      case 'Food & Groceries':
        return <ShoppingBag className="w-5 h-5 text-emerald-500" />;
      case 'Housing & Utilities':
        return <Home className="w-5 h-5 text-blue-500" />;
      case 'Installments & Debt':
        return <CreditCard className="w-5 h-5 text-rose-500" />;
      case 'Transport & Ride Apps':
        return <Car className="w-5 h-5 text-amber-500" />;
      case 'Shopping & Entertainment':
        return <Coffee className="w-5 h-5 text-purple-500" />;
      default:
        return <ShieldAlert className="w-5 h-5 text-teal-500" />;
    }
  };

  return (
    <div className="space-y-6 pb-20 lg:pb-8 animate-fadeIn">
      {/* Header & Controls */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-emerald-900 via-slate-900 to-teal-950 text-white shadow-xl border border-emerald-800/50 space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-emerald-400 text-xs font-semibold mb-1">
              <Sparkles className="w-4 h-4" />
              <span>{isAr ? 'مولد الميزانية الديناميكي بالمصري' : 'Dynamic Auto Budget Engine'}</span>
            </div>
            <h2 className="text-2xl font-black">
              {isAr
                ? `ميزانية شهر ${budget.month} ${budget.year}`
                : `Budget for ${budget.month} ${budget.year}`}
            </h2>
            <p className="text-xs text-slate-300 mt-1">
              {isAr
                ? 'تتأقلم الميزانية تلقائياً مع ارتفاع الأسعار والتغيرات الماليّة في مصر'
                : 'Adapts automatically to Egyptian inflation and salary changes'}
            </p>
          </div>

          <button
            onClick={handleGenerateAutoBudget}
            disabled={isGenerating}
            className="flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-black text-xs shadow-lg transition disabled:opacity-50"
          >
            <RefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
            <span>{isAr ? 'إعادة إنشاء الميزانية بالذكاء الاصطناعي' : 'Generate AI Budget'}</span>
          </button>
        </div>

        {errorMsg && (
          <div className="p-3 rounded-xl bg-rose-500/20 border border-rose-500/40 text-rose-300 text-xs flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 shrink-0" />
            <span>{errorMsg}</span>
          </div>
        )}

        {/* Salary Input Box */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4 border-t border-slate-800 text-xs">
          <div>
            <label className="block text-slate-400 mb-1 font-bold">
              {isAr ? 'إجمالي الدخل / المرتب الشهري (EGP)' : 'Monthly Income'}
            </label>
            <input
              type="number"
              value={salaryInput}
              onChange={(e) => setSalaryInput(e.target.value)}
              placeholder={isAr ? 'أدخل المرتب مثلاً 20000' : 'Enter salary e.g. 20000'}
              className="w-full px-3.5 py-2 rounded-xl bg-slate-800 border border-slate-700 text-white font-bold text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
            />
          </div>

          <div>
            <label className="block text-slate-400 mb-1 font-bold">
              {isAr ? `نسبة الادخار المستهدفة: ${savingsPercent}%` : `Savings Target: ${savingsPercent}%`}
            </label>
            <input
              type="range"
              min="5"
              max="40"
              step="5"
              value={savingsPercent}
              onChange={(e) => setSavingsPercent(parseInt(e.target.value, 10))}
              className="w-full accent-emerald-500 cursor-pointer"
            />
          </div>
        </div>
      </div>

      {/* Progress Categories Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {budget.categories.map((cat, idx) => {
          const percentUsed = Math.min(
            100,
            Math.round(((cat.spentAmount || 0) / (cat.allocatedAmount || 1)) * 100)
          );
          const isOverbudget = (cat.spentAmount || 0) > cat.allocatedAmount;

          return (
            <div
              key={idx}
              className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-3"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-slate-100 dark:bg-slate-800">
                    {getCategoryIcon(cat.category)}
                  </div>
                  <div>
                    <h4 className="font-bold text-sm text-slate-900 dark:text-white">
                      {isAr ? cat.categoryAr : cat.category}
                    </h4>
                    <span className="text-xs text-slate-500">
                      {isAr
                        ? `المخصص: ${formatCurrency(cat.allocatedAmount, 'EGP', lang)}`
                        : `Allocated: ${formatCurrency(cat.allocatedAmount, 'EGP', lang)}`}
                    </span>
                  </div>
                </div>

                <div className="text-left font-bold text-sm">
                  <span className={isOverbudget ? 'text-rose-600' : 'text-slate-900 dark:text-white'}>
                    {formatCurrency(cat.spentAmount || 0, 'EGP', lang)}
                  </span>
                  <span className="text-xs text-slate-400 block">{percentUsed}%</span>
                </div>
              </div>

              {/* Progress Bar */}
              <div className="w-full bg-slate-100 dark:bg-slate-800 h-2.5 rounded-full overflow-hidden">
                <div
                  className={`h-full rounded-full transition-all duration-500 ${
                    isOverbudget ? 'bg-rose-600' : percentUsed > 80 ? 'bg-amber-500' : 'bg-emerald-500'
                  }`}
                  style={{ width: `${percentUsed}%` }}
                />
              </div>

              {isOverbudget && (
                <div className="p-2 rounded-lg bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800 text-[11px] text-rose-800 dark:text-rose-300 font-bold flex items-center gap-1.5">
                  <AlertTriangle className="w-3.5 h-3.5 shrink-0" />
                  <span>تجاوزت الميزانية المحددة لهذه الفئة! تنبيه من الكوتش المالي.</span>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
