import { z } from 'zod';

export const aiChatSchema = z.object({
  message: z.string().trim().min(1, 'Message cannot be empty'),
  intent: z
    .enum(['coach_chat', 'auto_budget', 'debt_plan', 'fraud_check', 'savings_hedge'])
    .optional()
    .default('coach_chat'),
  history: z
    .array(
      z.object({
        role: z.enum(['user', 'model']),
        text: z.string(),
      })
    )
    .optional()
    .default([]),
});

export const ocrAnalyzeSchema = z.object({
  base64Image: z.string().min(1, 'base64Image is required'),
  mimeType: z.string().optional().default('image/jpeg'),
});

export const voiceCommandSchema = z.object({
  spokenText: z.string().min(1, 'spokenText is required'),
});

export const walletCreateSchema = z.object({
  name: z.string().min(1, 'اسم المحفظة مطلوب'),
  nameAr: z.string().optional().default('محفظة جديدة'),
  type: z.enum(['cash', 'bank', 'card', 'savings', 'wallet', 'credit']),
  balance: z.number().default(0),
  currency: z.enum(['EGP', 'USD', 'SAR', 'EUR']).default('EGP'),
  accountNumber: z.string().optional(),
  icon: z.string().optional().default('Wallet'),
  color: z.string().optional().default('bg-emerald-600'),
  isPrimary: z.boolean().optional(),
});

export const transactionCreateSchema = z
  .object({
    title: z.string().min(1),
    amount: z.number().positive(),
    currency: z.enum(['EGP', 'USD', 'SAR', 'EUR']).default('EGP'),
    type: z.enum(['expense', 'income', 'transfer']),
    category: z.enum([
      'Food & Groceries',
      'Housing & Utilities',
      'Bills & Subscriptions',
      'Transport & Ride Apps',
      'Installments & Debt',
      'Health & Education',
      'Family & Allowances',
      'Shopping & Entertainment',
      'Emergency & Savings',
      'Income & Salary',
    ]),
    walletId: z.string().min(1),
    destinationWalletId: z.string().optional(),
    paymentMethod: z
      .enum([
        'InstaPay',
        'Vodafone Cash',
        'CIB Bank',
        'Fawry',
        'Cash',
        'Visa/Mastercard',
        'Valu',
        'B.TECH / Aman',
      ])
      .default('InstaPay'),
    date: z.string().default(() => new Date().toISOString().split('T')[0]),
    merchant: z.string().optional(),
    notes: z.string().optional(),
    receiptUrl: z.string().optional(),
    isDuplicate: z.boolean().optional(),
    aiTag: z.string().optional(),
    hasAnomaly: z.boolean().optional(),

    relatedDebtId: z.string().optional(),
    relatedBillId: z.string().optional(),
    relatedObligationId: z.string().optional(),
    relatedInstallmentId: z.string().optional(),
  })
  .superRefine((data, ctx) => {
    if (data.type === 'transfer') {
      if (!data.destinationWalletId || data.destinationWalletId.trim() === '') {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: 'Destination wallet is required for transfer transactions.',
          path: ['destinationWalletId'],
        });
      } else if (data.destinationWalletId === data.walletId) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: 'Destination wallet must differ from source wallet.',
          path: ['destinationWalletId'],
        });
      }
    }
  });

export const categoryBudgetSchema = z.object({
  category: z.string(),
  categoryAr: z.string(),
  allocatedAmount: z.number().nonnegative(),
  spentAmount: z.number().nonnegative().default(0),
  color: z.string().default('#10B981'),
  icon: z.string().default('ShoppingBag'),
});

export const budgetSetSchema = z.object({
  id: z.string().min(1),
  monthKey: z.string().optional(),
  month: z.string().default(() => new Date().toLocaleString('ar-EG', { month: 'long' })),
  year: z.number().default(() => new Date().getFullYear()),
  totalIncome: z.number().nonnegative(),
  totalSalary: z.number().nonnegative().optional(),
  targetSavingsPercent: z.number().min(0).max(100).default(20),
  savingsTargetPercent: z.number().min(0).max(100).optional(),
  allocatedSavings: z.number().nonnegative().default(0),
  categories: z.array(categoryBudgetSchema),
  autoGenerated: z.boolean().optional(),
});

export const goalCreateSchema = z.object({
  id: z.string().optional(),
  title: z.string().min(1, 'اسم الهدف مطلوب'),
  titleAr: z.string().optional(),
  targetAmount: z.number().positive('مبلغ الهدف يجب أن يكون أكبر من 0'),
  currentAmount: z.number().nonnegative().default(0),
  targetDate: z.string().default(() => new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]),
  category: z.string().default('general'),
  icon: z.string().default('Target'),
  color: z.string().default('bg-blue-500'),
  monthlyTarget: z.number().nonnegative().default(0),
  riskLevel: z.enum(['Low', 'Medium', 'High']).default('Medium'),
  successProbability: z.number().min(0).max(100).default(80),
}).transform((data) => ({
  ...data,
  titleAr: data.titleAr || data.title,
}));

export const billCreateSchema = z.object({
  id: z.string().optional(),
  title: z.string().min(1, 'عنوان الفاتورة مطلوب'),
  titleAr: z.string().optional(),
  biller: z.string().default('جهات المرافق'),
  amount: z.number().positive('مبلغ الفاتورة يجب أن يكون أكبر من 0'),
  dueDate: z.string().default(() => new Date().toISOString().split('T')[0]),
  isPaid: z.boolean().default(false),
  paymentMethod: z.enum([
    'InstaPay',
    'Vodafone Cash',
    'CIB Bank',
    'Fawry',
    'Cash',
    'Visa/Mastercard',
    'Valu',
    'B.TECH / Aman',
  ]).default('InstaPay'),
  fawryCode: z.string().optional(),
  icon: z.string().default('Zap'),
  urgency: z.enum(['high', 'medium', 'low']).default('medium'),
  notes: z.string().optional(),
}).transform((data) => ({
  ...data,
  titleAr: data.titleAr || data.title,
}));

export const subscriptionCreateSchema = z.object({
  id: z.string().optional(),
  name: z.string().min(1, 'اسم الاشتراك مطلوب'),
  provider: z.string().default('خدمة رقمية'),
  amount: z.number().positive('مبلغ الاشتراك يجب أن يكون أكبر من 0'),
  currency: z.enum(['EGP', 'USD', 'SAR', 'EUR']).default('EGP'),
  cycle: z.enum(['monthly', 'yearly']).default('monthly'),
  nextDueDate: z.string().default(() => new Date().toISOString().split('T')[0]),
  paymentMethod: z.enum([
    'InstaPay',
    'Vodafone Cash',
    'CIB Bank',
    'Fawry',
    'Cash',
    'Visa/Mastercard',
    'Valu',
    'B.TECH / Aman',
  ]).default('Visa/Mastercard'),
  category: z.enum([
    'Food & Groceries',
    'Housing & Utilities',
    'Bills & Subscriptions',
    'Transport & Ride Apps',
    'Installments & Debt',
    'Health & Education',
    'Family & Allowances',
    'Shopping & Entertainment',
    'Emergency & Savings',
    'Income & Salary',
  ]).default('Bills & Subscriptions'),
  autoPay: z.boolean().default(true),
  icon: z.string().default('Tv'),
  status: z.enum(['active', 'paused', 'cancelled']).default('active'),
  notes: z.string().optional(),
});

export const installmentCreateSchema = z.object({
  id: z.string().optional(),
  title: z.string().min(1),
  titleAr: z.string().optional(),
  principalAmount: z.number().positive(),
  remainingAmount: z.number().nonnegative(),
  monthlyPayment: z.number().positive(),
  interestRate: z.number().min(0).default(0),
  dueDay: z.number().min(1).max(31).default(1),
  provider: z.string().default('Valu'),
  status: z.enum(['ACTIVE', 'PAID_OFF']).default('ACTIVE'),
  notes: z.string().optional(),
});

export const profileOnboardingSchema = z.object({
  displayName: z.string().min(1).max(100).optional(),
  salary: z.number().nonnegative().optional().default(0),
  monthlyIncome: z.number().nonnegative().optional(),
  currency: z.enum(['EGP', 'USD', 'SAR', 'EUR']).default('EGP'),
  country: z.string().default('EG'),
  language: z.enum(['ar', 'en']).default('ar'),
});

export const profileUpdateSchema = z.object({
  displayName: z.string().min(1).max(100).optional(),
  salary: z.number().nonnegative().optional(),
  monthlyIncome: z.number().nonnegative().optional(),
  currency: z.enum(['EGP', 'USD', 'SAR', 'EUR']).optional(),
  country: z.string().optional(),
  language: z.enum(['ar', 'en']).optional(),
  emergencyFundMonths: z.number().min(1).max(24).optional(),
});

export const systemConfigSchema = z.object({
  flags: z.object({
    voiceAssistant: z.boolean(),
    emergencyMode: z.boolean(),
    familyWallet: z.boolean(),
    ocrReceiptScanner: z.boolean(),
    aiAutoBudget: z.boolean(),
    geminiProRouting: z.boolean(),
    whatsappIntegration: z.boolean(),
    instapayDirectSync: z.boolean(),
  }),
});
