import {
  Wallet,
  Transaction,
  Budget,
  Goal,
  Subscription,
  Bill,
  HealthScoreBreakdown,
  AIAgent,
  InsightTimelineItem,
  FamilyMember,
  Challenge,
} from '../types';

export const initialWallets: Wallet[] = [];

export const initialTransactions: Transaction[] = [];

export const initialBudget: Budget = {
  id: '',
  month: 'أغسطس',
  year: 2026,
  totalIncome: 0,
  totalSalary: 0,
  targetSavingsPercent: 20,
  savingsTargetPercent: 20,
  allocatedSavings: 0,
  autoGenerated: true,
  categories: [
    {
      category: 'Food & Groceries',
      categoryAr: 'الأكل والسوبرماركت',
      allocatedAmount: 0,
      spentAmount: 0,
      color: '#10B981',
      icon: 'ShoppingBag',
    },
    {
      category: 'Housing & Utilities',
      categoryAr: 'السكن والفواتير',
      allocatedAmount: 0,
      spentAmount: 0,
      color: '#3B82F6',
      icon: 'Home',
    },
    {
      category: 'Installments & Debt',
      categoryAr: 'الأقساط والالتزامات',
      allocatedAmount: 0,
      spentAmount: 0,
      color: '#EF4444',
      icon: 'CreditCard',
    },
    {
      category: 'Transport & Ride Apps',
      categoryAr: 'المواصلات وأوبر',
      allocatedAmount: 0,
      spentAmount: 0,
      color: '#F59E0B',
      icon: 'Car',
    },
    {
      category: 'Shopping & Entertainment',
      categoryAr: 'الترفيه والدليفري',
      allocatedAmount: 0,
      spentAmount: 0,
      color: '#8B5CF6',
      icon: 'Coffee',
    },
    {
      category: 'Emergency & Savings',
      categoryAr: 'الطوارئ والادخار',
      allocatedAmount: 0,
      spentAmount: 0,
      color: '#06B6D4',
      icon: 'ShieldAlert',
    },
  ],
};

export const initialGoals: Goal[] = [];

export const initialSubscriptions: Subscription[] = [];

export const initialBills: Bill[] = [];

export const initialHealthScore: HealthScoreBreakdown = {
  overallScore: 0,
  savingsRateScore: 0,
  debtRatioScore: 0,
  budgetDisciplineScore: 0,
  emergencyFundScore: 0,
  incomeStabilityScore: 0,
  recommendations: [],
};

export const aiAgents: AIAgent[] = [
  {
    id: 'coach',
    name: 'المستشار المالي',
    nameAr: 'كوتش ميزانية AI',
    role: 'Financial Coach',
    roleAr: 'المستشار المالي الشامل',
    avatarIcon: 'Bot',
    color: 'from-blue-600 to-indigo-600',
  },
  {
    id: 'budget',
    name: 'وكيل الميزانية',
    nameAr: 'خبير التقسيم المالي',
    role: 'Budget Master',
    roleAr: 'مخطط الميزانية والتضخم',
    avatarIcon: 'PieChart',
    color: 'from-emerald-600 to-teal-600',
  },
  {
    id: 'savings',
    name: 'وكيل الادخار',
    nameAr: 'خبير التوفير',
    role: 'Savings Specialist',
    roleAr: 'مكتشف الفرص والتوفير',
    avatarIcon: 'PiggyBank',
    color: 'from-amber-500 to-yellow-600',
  },
  {
    id: 'debt',
    name: 'وكيل الأقساط',
    nameAr: 'مستشار الديون',
    role: 'Debt Snowball',
    roleAr: 'مفكك الأقساط والديون',
    avatarIcon: 'ShieldAlert',
    color: 'from-rose-600 to-red-600',
  },
  {
    id: 'fraud',
    name: 'وكيل الأمان',
    nameAr: 'مكتشف الشبهات',
    role: 'Fraud & Duplicate Detector',
    roleAr: 'حارس المعاملات المكررة',
    avatarIcon: 'Lock',
    color: 'from-purple-600 to-indigo-700',
  },
];

export const initialTimeline: InsightTimelineItem[] = [];

export const initialFamilyMembers: FamilyMember[] = [];

export const initialChallenges: Challenge[] = [];
